name: Flutter_Analyzer

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter analyze